### ISSUE TITLE
Add source files of flowcharts to repo

### ISSUE THREAD

**Issue by J535D165** [UtrechtUniversity/SWORDS-UU#8]
Add source files of flowcharts to the repo and add instructions in which program to open them.

**Comment by J535D165** [comment]
This is annoying. Is draw.io a better solution? They use an open export format if I remember correctly.

**Comment by kequach** [comment]
I'll investigate and if that's the case, I'll migrate the flowcharts

**Comment by kequach** [comment]
Flowcharts were exported to draw.io. They are now openly available in /docs
